In [1]:
import pandas as pd 
df = pd.read_csv("prices.csv")

In [2]:
df.head()

   id        date    market commodity  price
0   0  2020-14-15  Nakasero     MAIZE    500
1   1  2020-03-30       NaN     BEANS  -2000
2   2  2021-09-08    mukono     MAIZE    500
3   3  2022-04-08    mukono     MAIZE    500
4   4  2022-02-20  Nakasero     Maize    500

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1010 entries, 0 to 1009
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         1010 non-null   int64
 1   date       1010 non-null   str
 2   market     821 non-null    str
 3   commodity  1010 non-null   str
 4   price      1010 non-null   int64
dtypes: int64(2), str(3)
memory usage: 39.6 KB

In [4]:
df.describe(include='all')

                 id        date    market commodity        price
count   1010.000000        1010       821      1010  1010.000000
unique          NaN         628         4         4          NaN
top             NaN  2020-14-15  Nakasero     BEANS          NaN
freq            NaN          29       215       280          NaN
mean     494.778218         NaN       NaN       NaN   366.336634
std      291.211182         NaN       NaN       NaN   562.677520
min        0.000000         NaN       NaN       NaN -2000.000000
25%      242.250000         NaN       NaN       NaN   500.000000
50%      494.500000         NaN       NaN       NaN   500.000000
75%      746.750000         NaN       NaN       NaN   500.000000
max      999.000000         NaN       NaN       NaN   500.000000